# Generated by Django 4.2 on 2025-01-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_videopost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='video_url',
        ),
    ]
